def drawHangMan(lives):
    if lives == 5:
        print("  __")
        print(" |/")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print("_|__")
    elif lives == 4:
        print("  _______")
        print(" |/      |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print("_|__")
    elif lives == 3:
        print("  _______")
        print(" |/      |")
        print(" |      (_)")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print("_|__")
    elif lives == 2:
        print("  _______")
        print(" |/      |")
        print(" |      (_)")
        print(" |      \\|/")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print("_|__")
    elif lives == 1:
        print("  _______")
        print(" |/      |")
        print(" |      (_)")
        print(" |      \\|/")
        print(" |       |")
        print(" |")
        print(" |")
        print(" |")
        print("_|__")
    else:
        print("  _______")
        print(" |/      |")
        print(" |      (_)")
        print(" |      \\|/")
        print(" |       |")
        print(" |      / \\")
        print(" |")
        print(" |")
        print("_|__")
